### ISSUE TITLE
Custom Import doesn't work

### ISSUE THREAD

**Issue by puneet0191** [DeskPRO/deskpro-importer-tools#25]
I have been trying to import tickets from my current tool to Deskpro, I have followed the instructions given here  https://github.com/DeskPRO/deskpro-importer-tools/blob/master/custom/README.md 

1) Downloaded the zip and moved deskpro-importer-tools-master into DeskPRO's /bin/ directory
2) I created a new folder for my current tool, and kept that inside importer directory, so this is how the file structure looks like now 
Deskpro/bin/deskpro-importer-tools-master/importers/mytoolfolder/mytoolname.php (copied from custom.php present in custom folder)
3)  Since I don't need to build my own custom importer, I already have all the json files prepared for all the tickets that I want to import, I just prepared the directory structure. 
Deskpro/bin/deskpro-importer-tools-master/importers/mytoolfolder/content/1/ticket/xyz.json 
4) I checked the data integrity using https://github.com/DeskPRO/deskpro-importer-tools/blob/master/custom/README.md#how-to-run-import 
5) When integrity check  passed I just executed the import command, I can see success msg as output on the console, but I am still not able to see the ticket in the backend. 

![image](https://cloud.githubusercontent.com/assets/3048593/22564398/630bcf7c-e9aa-11e6-810d-f8a60642ca35.png)

but I also get these, 
![image](https://cloud.githubusercontent.com/assets/3048593/22564436/8720c458-e9aa-11e6-9129-ba73758a1222.png)

Not sure what is the relevance, can someone guide me what I should be doing to make this import work for my custom tool.

**Comment by syastrebov** [comment]
@puneet0191 you don't need to download and copy `deskpro-importer-tools-master` because you have already the json files to import. Creating custom tool is to simplify preparing importer's json files from an external source (e.g. another db, api etc).

You just need to set proper file path and directory structure like https://github.com/DeskPRO/deskpro-importer-tools/blob/master/custom/README.md#how-to-run-import:

1. So you have `/path/to/Deskpro/bin/deskpro-importer-tools-master/importers/mytoolfolder/content/1/ticket/xyz.json`, it looks correctly.

2. And then apply it using `php bin/import apply --input-path=/path/to/Deskpro/bin/deskpro-importer-tools-master/importers/mytoolfolder/content`

I don't see if the importer found the ticket json files in the attached log images or what command was used for applying it. `Export X collection. X was not found` means that no files to import were found in the following `input-path` directory. 

Please confirm you set correct `input-path` and the importer found your json files.

**Comment by chrispadfield** [comment]
@puneet0191 did this resolve your issue?

**Comment by puneet0191** [comment]
@chrispadfield Yes I did, I had to do figure out another way though, but thanks for the follow up guys.
